### ISSUE TITLE
[Marketplace] display red error page when create new solution from Azure marketplace

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#398]
- VSCode Version: 1.32.2
- OS Version: windows10
- Extension Version: 1.11.0-rc

Steps to Reproduce:

1. create new solution from Azure marketplace
2. it will display red error page when open IoT Edge Marketplace page, Just one second flashed , then 20 items of Azure IoT Edge Module Marketplace will display well.

This phenomenon does not appear when adding new module

**Comment by czgtest** [comment]
@formulahendry   this issue is stable repro on my windows10 . Please see bellow error

![image](https://user-images.githubusercontent.com/35018765/55225293-4976e980-524d-11e9-8fce-0cd0e3a8f035.png)

**Comment by formulahendry** [comment]
@czgtest 500 error is a separate issue, which is already fixed in 1.11.1: https://github.com/Microsoft/vscode-azure-iot-edge/blob/master/CHANGELOG.md#1111---2019-03-30

For `one second flashed error page`, please help check whether it could be always repro. Since it is one second flash and did not block user. Put it as P2

**Comment by blackchoey** [comment]
@czgtest Please verify whether this issue still exist

**Comment by czgtest** [comment]
this issue still repro on Windows 10 when user create new project from Azure marketplace.

**Comment by konichi3** [comment]
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team
